### ISSUE TITLE
用了别人的代码，提都不提一下，这样子好么？

### ISSUE THREAD

**Issue by qingyongai** [CoXier/AppMethodTracking#1]
rt

**Comment by SamanLan** [comment]
+1

**Comment by Mr-wangyong** [comment]
+1

**Comment by BolexLiu** [comment]
+1

**Comment by CoXier** [comment]
Thanks for your feed back. At first I am inspired by [AppMethodOrder](https://github.com/zjw-swun/AppMethodOrder), but my core code is different from it.

I am very sorry for I take some same strategies .
*  How to compatible Windows os
*  How to generate trace info

# But you guys ！

# Have you guys ever looked through my code?
# Have you guys evet used this lib?

* The same idea is we both use `dmtracedump` tool .But  I directly get `trace info` from command line rather than `txt` file.
* I don't know AppMethodOrder how to filter method.But you can compare my way with it.
* I generate HMTL output and it supports folding methods. [A live demo](http://coxier.cn/AppMethodTracking.html) is here.
The HTML code is generated by groovy code.Please see [HtmlGenerator](https://github.com/CoXier/AppMethodTracking/blob/master/method-tracking/src/main/groovy/com/uniquestudio/HtmlGenerator.groovy)
* I use groovy project to develop plugin rather than `build.gradle` 

At last can you use English on GitHub?Even if my English is poor ,I persevere in using it.**Github is not only for you Chinese.**

**Comment by BolexLiu** [comment]
- I do not object to using English on GIthub. But this can not be used to show off your skills. So it makes me feel nausea and discomfort.
- 同样是中国人，用中文也没什么不好。不需要断章取义。

**Comment by qingyongai** [comment]
I just said you have used someone else's code, it's true.

**Comment by CoXier** [comment]
You can list all code which you think from someone else. @qingyongai

**Comment by waddwaw** [comment]
I do not object to using English on GIthub. But this can not be used to show off your skills. So it makes me feel nausea and discomfort.
同样是中国人，用中文也没什么不好。不需要断章取义。

**Comment by CoXier** [comment]
I don't want to focus on why you don't use English . In my answer , I have explain your issue clearly .As for English ,it's just a suggestion.

**Comment by BolexLiu** [comment]
You dug yourself a pit and buried it yourself. interesting. 2333

**Comment by Harlber** [comment]
`At last can you use English on GitHub?Even if my English is poor ,I persevere in using it.Github is not only for you Chinese.`
issue本身就是交流用的。人家用中文提，你用中文回，这是一种礼仪，我们好多人英文都不好，看不懂您高尚的英文。
